server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memory_forge_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 你的MySQL密码
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5

  devtools:
    restart:
      enabled: true

  mail:
    host: smtp.qq.com
    port: 587
    username: 你的QQ号@qq.com
    password: 你的QQ邮箱SMTP授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: 随机填一串长字符
  expiration: 604800000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

ai:
  deepseek:
    api-key: 你的DeepSeek_API_Key
    base-url: https://api.deepseek.com
    model: deepseek-chat
